receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  # Add resource attributes for better identification
  resource:
    attributes:
      - key: service.name
        value: claude-code
        action: upsert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: claude_code
    const_labels:
      environment: production

  # Datadog exporter (Optional)
  datadog:
    api:
      site: ${DD_SITE}
      key: ${DD_API_KEY}
    metrics:
      endpoint: https://api.${DD_SITE}
      resource_attributes_as_tags: true
    traces:
      endpoint: https://trace.agent.${DD_SITE}

  # Optional: Also log metrics for debugging
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [prometheus, debug]

    # Datadog pipeline (enabled when DD_API_KEY is set)
    metrics/datadog:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [datadog]

  extensions: []
