receivers:
  hostmetrics:
    scrapers:
      load:
      cpu:
      disk:
      filesystem:
      memory:
      network:
      paging:
      process:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  # Add resource attributes for better identification
  resource:
    attributes:
      - key: service.name
        value: claude-code
        action: upsert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: claude_code
    const_labels:
      environment: production

  # Optional: Also log metrics for debugging
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch, resource]
      exporters: [prometheus, debug]

  extensions: []
